--Enable Extra Units Lite
{
armzapper = {
health = 280,
speed = 171.0, },
cortorch = {
health = 1350, 
weapondefs = {
flame_thrower = {
areaofeffect = 48,
avoidfeature = false,
burst = 20,
burstrate = 0.05,
cegtag = "burnflame-anim",
colormap = "1 0.95 0.9 0.032   0.55 0.55 0.40 0.028   0.40 0.28 0.19 0.024   0.033 0.018 0.011 0.04   0.0 0.0 0.0 0.01",
craterareaofeffect = 0,
craterboost = 0,
cratermult = 0,
edgeeffectiveness = 0.15,
explosiongenerator = "custom:burnblack",
firestarter = 100,
flamegfxtime = 1,
bounceRebound = 0.8,
bounceSlip = 1.0,
impulseboost = 0,
impulsefactor = 0,
intensity = 0.6,
name = "FlameThrower",
noselfdamage = true,
range = 280,
reloadtime = 1.4,
rgbcolor = "1 0.94 0.88",
rgbcolor2 = "0.9 0.84 0.8",
sizegrowth = 0.8,
soundhitdry = "flamhit1",
soundhitwet = "sizzle",
soundstart = "flamhvy1",
soundhitvolume = 7.5,
soundstartvolume = 5.3,
soundtrigger = false,
sprayangle = 100,
tolerance = 2500,
turret = true,
weapontimer = 1,
weapontype = "Flame",
weaponvelocity = 295,
damage = {
default = 16,
vtol = 3,
},
},
},
},
armshockwave = {
metalcost = 820,
health = 3220,
weapondefs = {
hllt_bottom = {
sprayangle = 2250,
reloadtime = 4.5,
burst = 5,
burstrate = 0.1666,
		},
	},
},
armvp = {
buildoptions = {
[11] = "armzapper",
},
},
coravp = {
buildoptions = {
[1] =	 "coracv",
[2] =	 "corsala",
[3] =	 "correap",
[4] =	 "corparrow",
[5] =	 "corgol",
[6] =	 "corban",
[7] =	 "cormart",
[8] =	 "corvroc",
[9] =	 "cortrem",
[10] =	 "corsent",
[11] =	 "cormabm",
[12] =	 "coreter",
[13] =	 "corvrad",
[14] =  "cortorch",
[15] =  "corgatreap",
[16] =  "corftiger",
[17] =  "corforge",
[18] =  "corsiegebreaker",
[19] =  "corvac",
[20] =  "corphantom",
},
},
coralab = {
buildoptions = {
[18] = "cordeadeye",
},
},
armshltx = {
buildoptions = {
[7] = "armassimilator",
[8] = "armmeatball",
},
},
corack = {
buildoptions = {
	"corfus",
			"corfus",
			"corafus",
			"corgant",
			"corageo",
			"corbhmth",
			"cormoho",
			"cormexp",
			"cormmkr",
			"coruwadves",
			"coruwadvms",
			"corarad",
			"corshroud",
			"corfort",
			"corasp",
			"cortarg",
			"corsd",
			"corgate",
			"cortoast",
			"corvipe",
			"cordoom",
			"corflak",
			"corscreamer",
			"cortron",
			"corfmd",
			"corsilo",
			"corint",
			"corbuzz",
			"corlab",
			"coralab",
			"cornanotct2",
                        "cormwall",
},
},
coraca = {
buildoptions = {
	"corfus",
			"corafus",
			"corgant",
			"corageo",
			"corbhmth",
			"cormoho",
			"cormexp",
			"cormmkr",
			"coruwadves",
			"coruwadvms",
			"corarad",
			"corshroud",
			"corfort",
                        "cormwall",
			"corasp",
			"cortarg",
			"corsd",
			"corgate",
			"cortoast",
			"corvipe",
			"cordoom",
			"corflak",
			"corscreamer",
			"cortron",
			"corfmd",
			"corsilo",
			"corint",
			"corbuzz",
			"corlab",
			"coralab",
			"cornanotct2",
},
},
coracv = {
buildoptions = {
			[1] = "corfus",
			[2] = "corafus",
			[3] = "corageo",
			[4] = "corbhmth",
			[5] = "cormoho",
			[6] = "cormexp",
			[7] = "cormmkr",
			[8] = "coruwadves",
			[9] = "coruwadvms",
			[10] = "corarad",
			[11] = "corshroud",
			[12] = "corfort",
                        [13] = "cormwall",
			[14] = "corasp",
			[15] = "cortarg",
			[16] = "corsd",
			[17] = "corgate",
			[18] = "cortoast",
			[19] = "corvipe",
			[20] = "cordoom",
			[21] = "corflak",
			[22] = "corscreamer",
			[23] = "cortron",
			[24] = "corfmd",
			[25] = "corsilo",
			[26] = "corint",
			[27] = "corbuzz",
			[28] = "corvp",
			[29] = "coravp",
			[30] = "corgant",
                        [31] = "cornanotct2",
},
},
armack = {
buildoptions = {
                        "armfus",
			"armafus",
			"armckfus",
			"armshltx",
			"armageo",
			"armgmm",
			"armmoho",
			"armmmkr",
			"armuwadves",
			"armuwadvms",
			"armarad",
			"armveil",
			"armfort",
                        "armlwall",
			"armasp",
			"armtarg",
			"armsd",
			"armgate",
			"armamb",
			"armpb",
			"armanni",
			"armflak",
			"armmercury",
			"armemp",
			"armamd",
			"armsilo",
			"armbrtha",
			"armvulc",
			"armdf",
			"armlab",
			"armalab",
                        "armnanotct2",
                       "armshockwave",
},
},
armaca = {
buildoptions = {
	"armfus",
			"armafus",
			"armckfus",
			"armageo",
			"armuwageo",
			"armgmm",
			"armmoho",
			"armmmkr",
			"armuwadves",
			"armuwadvms",
			"armarad",
			"armveil",
			"armfort",
			"armasp",
			"armfasp",
			"armtarg",
			"armsd",
			"armgate",
			"armamb",
			"armpb",
			"armanni",
			"armflak",
			"armmercury",
			"armemp",
			"armamd",
			"armsilo",
			"armbrtha",
			"armvulc",
			"armdf",
			"armap",
			"armaap",
			"armplat",
			"armshltx",
                         "armlwall",
                        "armnanotct2",
                       "armshockwave",
},
},
armacv = {
buildoptions = {
[13] = "armlwall",
[14] = "armasp",
[15] = "armtarg",
[16] = "armsd",
[17] = "armgate",
[18] = "armamb",
[19] = "armpb",
[20] = "armanni",
[21] = "armflak",
[22] = "armmercury",
[23] = "armemp",
[24] = "armamd",
[25] = "armsilo",
[26] = "armbrtha",
[27] = "armvulc",
[28] = "armdf",
[29] = "armvp",
[30] = "armavp",
[31] = "armshltx",
[32] = "armnanotct2",
[33] = "armshockwave",
},
},
armacsub = {
buildoptions = {
[16] = "armnanotc2plat",
},
},
coracsub = {
buildoptions = {
[16] = "cornanotc2plat",
[17] = "legnanotc2plat",
},
},
corvac = {
buildoptions = {
[1] = "corch",
[2] = "cormex",
[3] = "corsolar",
[4] = "corwin",
[5] = "cormstor",
[6] = "corestor",
[7] = "corrad",
[8] = "corjamt",
[9] = "cornanotc",
[10] = "corfort",
[11] = "cormwall",
[12] = "cormadsam",
[13] = "corhllt",
[14] = "corpun",
},
},
corforge = {
buildoptions = {
[1] = "cortorch",
[2] = "corsala",
[3] = "corftiger",
[4] = "corah",
[5] = "corvrad",
[6] = "coreter",
[7] = "corsolar",
[8] = "corexp",
[9] = "cormakr",
[10] = "coreyes",
[11] = "cordrag",
[12] = "cormaw",
[13] = "corrl",
[14] = "corhlt",
},
},
legaca = {
buildoptions = {
                        "corfus",
			"corafus",
			"legageo",
			"coruwageo",
			"legrampart",
			"legmoho",
			"cormexp",
			"cormmkr",
			"coruwadves",
			"legamstor",
			"corarad",
			"corshroud",
			"legforti",
			"corasp",
			"corfasp",
			"cortarg",
			"corsd",
			"corgate",
			"legacluster",
			"legbombard",
			"legbastion",
			"legflak",
			"leglraa",
			"legperdition",
			"legabm",
			"legsilo",
			"leglrpc",
			"legstarfall",
			"legap",
			"legaap",
			"corplat",
			"leggant",
                        "legnanotct2",
                        "cormwall",
},
},
legack = {
buildoptions = {
	                 "corfus",
			"corafus",
			"leggant",
			"legageo",
			"legrampart",
			"legmoho",
			"cormexp",
			"cormmkr",
			"coruwadves",
			"legamstor",
			"corarad",
			"corshroud",
			"legforti",
			"corasp",
			"cortarg",
			"corsd",
			"corgate",
			"legacluster",
			"legbombard",
			"legbastion",
			"legflak",
			"leglraa",
			"legperdition",
			"legabm",
			"legsilo",
			"leglrpc",
			"legstarfall",
			"leglab",
			"legalab",
                        "legnanotct2",
                        "cormwall",
},
},		
legacv = {
buildoptions = {
	[1] = "corfus",
			[2] = "corafus",
			[3] = "legageo",
			[4] = "legrampart",
			[5] = "legmoho",
			[6] = "cormexp",
			[7] = "cormmkr",
			[8] = "coruwadves",
			[9] = "legamstor",
			[10] = "corarad",
			[11] = "corshroud",
			[12] = "legforti",
			[13] = "corasp",
			[14] = "cortarg",
			[15] = "corsd",
			[16] = "corgate",
			[17] = "legacluster",
			[18] = "legbombard",
			[19] = "legbastion",
			[20] = "legflak",
			[21] = "leglraa",
			[22] = "legperdition",
			[23] = "legabm",
			[24] = "legsilo",
			[25] = "leglrpc",
			[26] = "legstarfall",
			[27] = "legvp",
			[28] = "legavp",
			[29] = "leggant",
			[30] = "legnanotct2",
			[31] = "cormwall",
},
},
}
